import ContactForm from '@/components/contact/ContactForm';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Contact Us - DINCT',
  description: 'Generated by create next app',
};

const Contact = () => {
  return (
    <div className="px-4">
      <ContactForm />
    </div>
  );
};

export default Contact;
